### ISSUE TITLE
Question: I am a user from exchange, we want migrate from parity to core-get

### ISSUE THREAD

**Issue by past2017** [etclabscore/core-geth#100]
I am a user from exchange, we want migrate from parity to core-geth
so what's the difference about rpc access between parity and core-geth

**Comment by q9f** [comment]
Hi, we can come up with a comparison of the APIs.

Which APIs do you usually use? The `eth,web3,net` namespaces should be the same at least.

**Comment by meowsbits** [comment]
Indeed, I would expect those namespaces @q9f mentioned to be the same. 

Here's a few more notes, and general overview: 

- Parity has some RPC methods which are prefixed with `parity_`, which won't exist on Geth.
- Parity has `signer` and `traces` modules, which will be different with Geth, probably comparable to methods under `personal` and `debug` respectively.  
- Parity and Geth use the same HTTP and WebSocket port, `8545` and `8546` respectively.
- Parity's default IPC path will be different, however (`~/.local/share/io.parity.ethereum/jsonrpc.ipc` on Linux and `~/.ethereum/geth.ipc` for Geth)
- Flag usage for the CLIs will vary, for Geth you'll want some appropriate combination of the following, which I've simply taken from `geth --help`

```
API AND CONSOLE OPTIONS:                                                                                                  
  --ipcdisable                        Disable the IPC-RPC server                                                 
  --ipcpath value                     Filename for IPC socket/pipe within the datadir (explicit paths escape it)
  --http                              Enable the HTTP-RPC server                                           
  --http.addr value                   HTTP-RPC server listening interface (default: "localhost")  
  --http.port value                   HTTP-RPC server listening port (default: 8545)  
  --http.api value                    API's offered over the HTTP-RPC interface                     
  --http.corsdomain value             Comma separated list of domains from which to accept cross origin requests (browser enforced)
  --http.vhosts value                 Comma separated list of virtual hostnames from which to accept requests (server enforced). Accepts '*' wildcard. (default: "localhost")
  --ws                                Enable the WS-RPC server                            
  --ws.addr value                     WS-RPC server listening interface (default: "localhost")    
  --ws.port value                     WS-RPC server listening port (default: 8546)                    
  --ws.api value                      API's offered over the WS-RPC interface             
  --ws.origins value                  Origins from which to accept websockets requests
```

**Comment by meowsbits** [comment]
Just FYI:
- Parity RPC docs: https://openethereum.github.io/wiki/JSONRPC
- Geth RPC docs: https://geth.ethereum.org/docs/rpc/server
