### ISSUE TITLE
create an --eth-protocol=[65|64|63] flag?

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/core-geth#109]
Just an idea to allow the Ethereum Protocol version to be user configurable, which would provide a simple fix for issues like the ones Besu and ~~Parity~~ OpenEthereum are having on ETC right now. https://github.com/openethereum/openethereum/issues/11744

https://github.com/etclabscore/core-geth/blob/master/eth/protocol.go#L43

**Comment by meowsbits** [comment]
`les.protocol` version would be a welcome addition, too, though I would think a second step after the `eth-protocol` feature.

**Comment by ziogaschr** [comment]
> `les.protocol` version would be a welcome addition, too, though I would think a second step after the `eth-protocol` feature.

@meowsbits `eth.protocols` has been handled in #244.
Do you want to handle the `les.protocol` in same PR or in a new one? Actually, I am not sure if it makes sense to handle `les.protocol` at the moment.
