### ISSUE TITLE
can not find peers

### ISSUE THREAD

**Issue by atoken-ops** [etclabscore/core-geth#116]
CoreGeth
Version: 1.11.5-stable
Git Commit: baa01737c4d75f950b7dbf7501e4584f01d1be81
Git Commit Date: 20200601
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.14.3
Operating System: linux
GOPATH=/usr/local/gopath
GOROOT=/usr/local/go

INFO [06-10|13:37:40.525] Disk storage enabled for ethash caches   dir=/opt/etc/geth/ethash count=3
INFO [06-10|13:37:40.525] Disk storage enabled for ethash DAGs     dir=/root/.ethash        count=2
INFO [06-10|13:37:40.525] Initialising Ethereum protocol           versions="[65 64 63]" network=1 dbversion=7
INFO [06-10|13:37:40.525] Loaded most recent local header          number=0 hash="d4e567…cb8fa3" td=17179869184 age=51y2mo3d
INFO [06-10|13:37:40.525] Loaded most recent local full block      number=0 hash="d4e567…cb8fa3" td=17179869184 age=51y2mo3d
INFO [06-10|13:37:40.525] Loaded most recent local fast block      number=0 hash="d4e567…cb8fa3" td=17179869184 age=51y2mo3d
INFO [06-10|13:37:40.526] Loaded local transaction journal         transactions=0 dropped=0
INFO [06-10|13:37:40.526] Regenerated local transaction journal    transactions=0 accounts=0
INFO [06-10|13:37:40.555] Allocated fast sync bloom                size=1.60GiB
INFO [06-10|13:37:40.578] New local node record                    seq=2 id=ff424bb6d989f813 ip=127.0.0.1 udp=30303 tcp=30303
INFO [06-10|13:37:40.579] Started P2P networking                   self=enode://745f87d01bc5f3bf55a1ba0503d465ba9b5ef731fa1fc5ee97bc8985a0edb177c
59d4dce48b4eba61c88935d230b9129c6f628c57ef5540fd180581bcb8f2d65@127.0.0.1:30303
INFO [06-10|13:37:40.581] IPC endpoint opened                      url=/opt/etc/geth.ipc
INFO [06-10|13:37:40.581] HTTP endpoint opened                     url=http://[::]:8545/ cors= vhosts=localhost
INFO [06-10|13:37:40.703] Initialized fast sync bloom              items=12356 errorrate=0.000 elapsed=147.775ms
INFO [06-10|13:37:55.579] Looking for peers                        peercount=0 tried=1 static=0
INFO [06-10|13:38:08.852] Looking for peers                        peercount=0 tried=31 static=0
INFO [06-10|13:38:18.914] Looking for peers                        peercount=0 tried=6  static=0
INFO [06-10|13:38:29.018] Looking for peers                        peercount=0 tried=3  static=0
INFO [06-10|13:38:39.185] Looking for peers                        peercount=0 tried=3  static=0
INFO [06-10|13:38:50.334] Looking for peers                        peercount=0 tried=4  static=0
INFO [06-10|13:39:00.501] Looking for peers                        peercount=0 tried=4  static=0
INFO [06-10|13:39:11.638] Looking for peers                        peercount=0 tried=4  static=0
INFO [06-10|13:45:17.842] Looking for peers                        peercount=0 tried=4  static=0
INFO [06-10|13:45:27.842] Looking for peers                        peercount=0 tried=4  static=0
INFO [06-10|13:45:37.843] Looking for peers                        peercount=0 tried=4  static=0
INFO [06-10|13:45:47.843] Looking for peers                        peercount=0 tried=4  static=0
INFO [06-10|13:45:57.843] Looking for peers                        peercount=0 tried=4  static=0
INFO [06-10|13:46:07.843] Looking for peers                        peercount=0 tried=4  static=0
INFO [06-10|13:46:17.844] Looking for peers                        peercount=0 tried=4  static=0
INFO [06-10|13:46:27.844] Looking for peers                        peercount=0 tried=4  static=0
INFO [06-10|13:46:37.844] Looking for peers                        peercount=0 tried=4  static=0
INFO [06-10|13:46:47.845] Looking for peers                        peercount=0 tried=4  static=0
INFO [06-10|13:46:57.845] Looking for peers                        peercount=0 tried=4  static=0
INFO [06-10|13:47:07.845] Looking for peers                        peercount=0 tried=4  static=0
INFO [06-10|13:47:17.845] Looking for peers                        peercount=0 tried=4  static=0
INFO [06-10|13:47:27.846] Looking for peers                        peercount=0 tried=4  static=0

**Comment by meowsbits** [comment]
Can you describe your networking configuration a little more? Anything out of the ordinary? Do you have a UPnP or NAT-PMP router available on the network?

Geth will try to map to port 30303 on UDP and TCP, and I don't see a record of this event's success in your logs. Increasing your log level to DEBUG (`--verbosity=4`) will show error messages in this case.

**Comment by atoken-ops** [comment]
netstat -nplt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:9933            0.0.0.0:*               LISTEN      13209/polkadot  
tcp        0      0 0.0.0.0:9933            0.0.0.0:*               LISTEN      13209/polkadot  
tcp        0      0 0.0.0.0:9933            0.0.0.0:*               LISTEN      13209/polkadot  
tcp        0      0 0.0.0.0:9933            0.0.0.0:*               LISTEN      13209/polkadot  
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      996/sshd        
tcp        0      0 127.0.0.1:9944          0.0.0.0:*               LISTEN      13209/polkadot  
tcp        0      0 0.0.0.0:30333           0.0.0.0:*               LISTEN      13209/polkadot  
tcp        0      0 0.0.0.0:10050           0.0.0.0:*               LISTEN      13506/zabbix_agentd
tcp        0      0 127.0.0.1:9001          0.0.0.0:*               LISTEN      31326/python    
tcp6       0      0 :::30303                :::*                    LISTEN      15492/geth      
tcp6       0      0 :::8545                 :::*                    LISTEN      15492/geth      
tcp6       0      0 :::10050                :::*                    LISTEN      13506/zabbix_agentd

ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:16:3e:14:12:75 brd ff:ff:ff:ff:ff:ff
    inet 10.8.3.46/24 brd 10.8.3.255 scope global eth0
       valid_lft forever preferred_lft forever

INFO [06-11|09:47:53.351] Initialized fast sync bloom              items=12356 errorrate=0.000 elapsed=192.783ms
DEBUG[06-11|09:47:55.277] Couldn't add port mapping                proto=tcp extport=30303 intport=30303 interface="UPnP or NAT-PMP" err="no UPnP or NAT-PMP router discovered"
DEBUG[06-11|09:47:55.278] Couldn't add port mapping                proto=udp extport=30303 intport=30303 interface="UPnP or NAT-PMP" err="no UPnP or NAT-PMP router discovered"
DEBUG[06-11|09:48:03.647] Removed dead node                        b=16 id=0970decfe54cafed ip=54.148.165.1 checks=0

**Comment by atoken-ops** [comment]
The problem has been solved,tks
