### ISSUE TITLE
Feat: Remote freezer interface definition

### ISSUE THREAD

**Issue by zcstarr** [etclabscore/core-geth#131]
Summary:
Currently the ancient store in core-geth is linked directly to writing data to disk. We have found that it might be beneficial to allow developers and users to have ancient storage that acts a service. The ancient storage service would provide the same functionality, but instead accept request over JSON-RPC. This will allow for people to write their own connectors for ancient storage. The full scope of current progress on this work is in the PR #103 . We need to define what the edges of the system for building custom freezer implementation should look like. Defining a developer and consumer workflow.

Acceptance Criteria
The goal here is to define the interfaces that we expect users and developers to use when working with a custom remote freezer.

**Comment by zcstarr** [comment]
Here's a thought

**Comment by meowsbits** [comment]
Ah fuck lol

**Comment by meowsbits** [comment]
Replaced by #130
