### ISSUE TITLE
connect to nodes that not have update(hard fork)

### ISSUE THREAD

**Issue by prettyCoders** [etclabscore/core-geth#148]
![图片](https://user-images.githubusercontent.com/36216120/88151276-14a65700-cc35-11ea-9aa7-1c802f64d827.png)

my node is a new node, if it always connect to nodes that not have update, so, my node is useless to me!
 the latest block height is 10841850, my peer`s latest block height is 10399145

![图片](https://user-images.githubusercontent.com/36216120/88151331-22f47300-cc35-11ea-8067-24d33584ecfc.png)

**Comment by meowsbits** [comment]
Can you please share the output of `geth version` and what flags you are using to run the program with?

From the screenshots, I see that your node's current block is 5,508,895, not yet synced.

**Comment by prettyCoders** [comment]
@meowsbits 
![图片](https://user-images.githubusercontent.com/36216120/88265306-d45fdb00-ccff-11ea-962c-d4b79325b9eb.png)
![图片](https://user-images.githubusercontent.com/36216120/88265375-f5283080-ccff-11ea-8cc3-fe0e1f59c9f9.png)

**Comment by meowsbits** [comment]
In this latest screenshot, your sync progress has now reached 10,514,492. I don't see anything out of the ordinary.

**Comment by prettyCoders** [comment]
@meowsbits 
https://etc.tokenview.com/cn/   The highestBlock is 10853399,I don't know why

**Comment by prettyCoders** [comment]
It may be connected ETH node. i think so, because the ETH highestBlock is 10519924

**Comment by meowsbits** [comment]
Did you use the `--classic` flag?

**Comment by prettyCoders** [comment]
Thanks,resolved my problem
