### ISSUE TITLE
Feat: dependabot-style PRs when the ethereum-json-rpc-spec changes

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/core-geth#15]
Migrated from: https://github.com/etclabscore/multi-geth-fork/issues/103
Original author: @BelfordZ

---

rel #99

**Comment by ziogaschr** [comment]
How do we check for spec updates? Is this just a document in a repo? Maybe we can use [wei/pull](https://github.com/wei/pull) GitHub Action here as well.

If not, can you share more info, as I can work on it if you like @meowsbits.

**Comment by meowsbits** [comment]
Hm.. this issue is an old and probably stale one. 

Since this issue was created we've added support for OpenRPC by reflection (which includes the spec'd methods). The dependabot PRs would have been useful if we wanted to update a static file (basically, the spec) that geth would serve at `rpc.discover`, but that's not really relevant or sensible anymore. 

If the spec changes and becomes incompatible with ours (since we meet it currently), then I would say it's up to the spec to bump their version number accordingly, and core-geth then until updating would just be implementing an _older_ version.

If we really want to be serious about assuring core-geth is aligned with the spec, then what comes to mind is a test that would `curl` the raw JSON spec and validate core-geth's `rpc.discover` result against it. Actually just typing this out loud starts to seem like a pretty decent test for the `rpc.discover` implementation anyways.

**Comment by ziogaschr** [comment]
@meowsbits I think we can close this one based on #295
