### ISSUE TITLE
Always looking for peers

### ISSUE THREAD

**Issue by prettyCoders** [etclabscore/core-geth#163]
Is there have any seed peers?

**Comment by prettyCoders** [comment]
![图片](https://user-images.githubusercontent.com/36216120/89004997-00014780-d336-11ea-859c-ac24bb003afe.png)
![图片](https://user-images.githubusercontent.com/36216120/89005003-055e9200-d336-11ea-8a82-6d75c70748b8.png)

**Comment by meowsbits** [comment]
Please include 
- the command you use to run geth
- the output of `geth version`
- logs if you can
- a context or timeline of the issue you're experiencing: When does the issue begin for you? How long has it continued? 

Common issues around network connectivity are often resolved by investigating:
- Are the necessary ports open? (eg. 30303)
- Does your node's network have a NatPMP router available? 
- Is your node able to access the Cloudflare DNS service? (Is your node in a country with a firewall that might prevent it?)

**Comment by prettyCoders** [comment]
![图片](https://user-images.githubusercontent.com/36216120/89366283-301b6280-d709-11ea-95df-8e5b3306982b.png)
What Happened?

**Comment by meowsbits** [comment]
Unfortunately, it is impossible to tell with these logs.  You can increase log verbosity by using the `--verbosity=4` flag, and that may help us see what's happening in more detail. 

Any other information you can provide about the operating context will be greatly appreciated.

**Comment by ziogaschr** [comment]
Closing this one as many things have been done with regards dns-lists since then and we haven't seen similar issues. Please re-open if you continue having this issue.
