### ISSUE TITLE
the node is not syncing using the flag --whitelist=10935623... for several days

### ISSUE THREAD

**Issue by leGift** [etclabscore/core-geth#172]
![Снимок экрана_2020-08-09_18-40-17](https://user-images.githubusercontent.com/39749341/89728336-ea93c800-da6f-11ea-9c7f-75debc8c5cfe.png)
Hi there,
CoreGeth
Version: 1.11.11-stable
Git Commit: 6cdc75730ca318bfc900e39c6b6a7daa538e8b07
Git Commit Date: 20200806
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.14.6
Operating System: linux
GOPATH=
GOROOT=/home/travis/.gimme/versions/go1.14.6.linux.amd64

Everything worked well before the attack. Now all the nodes that I add manually from the **etcnodes.org** do not pass validation.

`>Whitelist mismatch, dropping peer        id=e5f53294b3c30943 conn=inbound         number=10935623 hash="dd5a22…facccf" want="5cb67b…ca4f92"`

I added 99 nodes. No luck. But node was synced before and used by pool.

**Comment by meowsbits** [comment]
The whitelist drops peers who report blocks that don't match the specified whitelist block. Since the block specified has become obsolete, as the network has moved too far beyond that point in history, now you just need to remove the flag.

**Comment by leGift** [comment]
Thank you.
