### ISSUE TITLE
Doesn't sync

### ISSUE THREAD

**Issue by Joter271** [etclabscore/core-geth#175]
Ethereum classic chain doesn't sync or on wrong chain.  Syncing for over a week and at block 10675797.

Geth version: CoreGeth/v1.11.11-stable-6cdc7573/windows-amd64/go1.14.2
OS & Version: Windows Server 2016

Run command: geth --rpc=true --rpcport 8999 --rpcaddr 192.168.10.155 --rpcapi "eth,net,personal,web3,admin" --nat extip:XXXXX  --maxpeers "100"

**Comment by meowsbits** [comment]
Looks like you need to __add the `--classic` flag__! :grimacing: :joy:  You've synced with the ETH chain.

**Comment by Joter271** [comment]
Oh right. Forgot about that. Thanks.

**Comment by chiro-hiro** [comment]
> Looks like you need to **add the `--classic` flag**! grimacing joy You've synced with the ETH chain.

`core-eth` was developed by `etclabs`. I meant, Ethereum Class Labs why don't we set Ethereum Classic is default chain?. Plus, Ethereum Classic is original chain so I have no idea why do we need an extra `--classic` flag meanwhile `go-ethereum` must have `--forked` flag.

**Comment by meowsbits** [comment]
@chiro-hiro Please see the [comment here](https://github.com/etclabscore/core-geth/issues/1#issuecomment-662672090) for the thread on this. The primary reason is that it would be a major API-breaking change.
