### ISSUE TITLE
How much will reword for uncle in Era 1 (index 0):

### ISSUE THREAD

**Issue by jadeydi** [etclabscore/core-geth#177]
I found codes here,
https://github.com/ethereumproject/go-ethereum/blob/master/core/state_processor.go#L214

But for https://etc.tokenview.com/en/block/3262381 the uncle reward is  0.3125

Should not ?

```
	if era.Cmp(big.NewInt(0)) == 0 {
		r := new(big.Int)
		r.Add(uncle.Number, big8)    // 2,534,998 + 8              = 2,535,006
		r.Sub(r, header.Number)      // 2,535,006 - 2,534,999        = 7
		r.Mul(r, MaximumBlockReward) // 7 * 5e+18               = 35e+18
		r.Div(r, big8)               // 35e+18 / 8                            = 7/8 * 5e+18

		return r
	}
```

**Comment by meowsbits** [comment]
Era 1 (from [ECIP1017](https://github.com/ethereumproject/ECIPs/blob/master/ECIPs/ECIP-1017.md)) inherits the original uncle reward policy, unmodified from Ethereum, which prorates rewards on depth for uncle miners.

What you're seeing on TokenView is the reward for the _uncles-including miner_ (who won the block), in the form of a static 1/32 of the block reward per included uncle, but the code is for the miners of the uncle blocks. You can find the uncle-miner rewards here: https://etc.tokenview.com/en/uncleblock/3262381

Two entities get rewarded for uncles on the chain:
- The main block miner (`coinbase` address) gets a bonus for including uncles
- The uncles' block miner(s) get a smaller reward for having mined the uncles

```
>>> 5 * (2*1/32)

  5 × 2 × (1 / 32)

   = 0.3125            <-- uncles inclusion "bonus" for 2 uncles

>>> 0.3125 + 5     <-- plus 5 ETC block reward for mining block 3262381

  0.3125 + 5

   = 5.3125   
```

**Comment by jadeydi** [comment]
@meowsbits thanks
