### ISSUE TITLE
feature: add an ethash sealing option for --dev mode

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/core-geth#188]
Rel https://github.com/etclabscore/core-geth/issues/187

Currently `--dev` mode uses Clique consensus. This ticket documents a request for an Ethash option for the developer mode.

This would enable
- block production with a locked or absentee etherbase
- Ethash-sealed block consensus field values (eg. difficulty, mix, nonce)

This feature (like `--dev` mode as-is) is essentially an iteration of a convenience/preset flag; the functionality can be created/replicated with existing tools and options by following the pattern of setting up a local or custom config and network.

**Comment by ziogaschr** [comment]
The `--dev` was using ethash before and was replaced by Clique with [this PR](https://github.com/ethereum/go-ethereum/pull/15323/files).

If we want to bring it back, we can use `--dev.etchash` as @meowsbits suggested [here](https://github.com/etclabscore/core-geth/issues/187#issuecomment-695832761) and revert the logic from the upstream PR.

**Comment by meowsbits** [comment]
Nice find! 

From a comment there:

> Since forever we've had --dev in order to spin up a developer chain. Unfortunately it had quite a few issues:
> 
>   - Being based on ethash, it was wasting an entire CPU core to keep mining non-stop
>   - Mining non-stop made the block time converge to 15 seconds, annoying to test
>   - Running a start/stop script to only mine on transactions is cumbersome

I think the core reasons for wanting an `Ethash` dev mode back are well-enough documented above. Although I think it is worth stressing that a development mode should, in my opinion, at least be able to simulate production as nearly as possible. Congruent data schemas (block headers) is not too much to ask in this regard.

Here's how I think we can address the above complaints about the original Ethash-development mode implementation.

- Use fake PoW with Poisson-distributed emission intervals, ala https://github.com/etclabscore/core-geth/pull/180. This removes the need to dedicate a CPU, and exposes emission rate configuration (doesn't have to be block/15 seconds).
- I don't see a need to handle a block-emission-if-transaction mechanism. Not only can it be solved with a script (though "cumbersome"), but I'm sure there's a way we can handle that later, either with an additional option/flag, a defaultily-available "cumbersome" script for the dev-mode console, etc...

**Comment by BelfordZ** [comment]
FWIW (also not sure this really belongs in this issue, but ahhh what the hell) Heres what I'd like dev mode to do by default:

1. create a passwordless personal account (always unlocked, ideally)
2. using this account as etherbase, start 1 miner thread
3. gasPrice limit to 0 allowing free tx's.
4. using etherbase account, create faucet contract
5. set the etherbase of miner to be the faucet contract

Now, if I want to get some dev-test-net tokens in address A B and C, I can simply send a (free) transaction to the faucet, being given some test ETC in return.

This pattern extends itself to mordor and other PoW testnets, where we could add an option which when provided in combination with `--mordor`, would start a testnet node with the same pattern above. This would make it easy to start new faucet contracts for our testnets.

**Comment by ziogaschr** [comment]
Thanks a lot for your input @BelfordZ. I didn't had all those in mind.

1 & 2. it creates one already and you can use your own using `--miner.etherbase=0x...`
3. do you want this to be the default, or you are fine setting `--miner.gasprice=0`?

The miner account get enough ETC in the genesis.

4 & 5. Can be implemented of course but I would think it is not part of core-geth context.

### Sidenotes: 

1. if `--datadir` is set in `--dev` mode, then the chain is persisted on disk
2. when `--dev` is set, then `--[classic|mordor|...]` cannot be set 

### Idea

We can have a wrapper command or script (in core-geth or outside) that is able to:

1. create a genesis for any chain `--[classic|mordor|...]` using `echainspec` and modifying the output
2. init core-geth from the above genesis in step 1
3. start core-geth with the correct params for PoA or PoW in `--dev` mode and with gasPrice=0.
4. deploy a faucet contract
5. set etherbase to faucet

@BelfordZ what do you think?
@meowsbits can you verify that the above is correct, mainly with 4 & 5 and if a cmd already exists in core-geth. I remember that someone wanted puppeth to be removed from within core-geth.
