### ISSUE TITLE
downloader.go: findAncestor invalid memory address or nil pointer dereference (known, but nil header)

### ISSUE THREAD

**Issue by zhangsj** [etclabscore/core-geth#192]
Version: 1.11.5-stable update to v1.11.14
old version Version: 1.11.5-stable
new version CoreGeth/v1.11.14-stable-b711e954/linux-amd64/go1.15.2
ubuntu 16.04

command
 geth --classic --datadir /opt/etc -rpcvhosts * --rpcaddr 0.0.0.0  --rpcaddr 0.0.0.0 --rpc --http --http.api eth,net,web3,txpool

![image](https://user-images.githubusercontent.com/7639036/94354765-2252df80-00b1-11eb-96ed-0184c1723dbe.png)

**Comment by iquidus** [comment]
Unrelated to the nil pointer dereference, but your flags are duplicating. --http and --rpc do the same thing (--rpc is deprecated, replaced by http)

```
geth --classic --datadir /opt/etc -rpcvhosts * --rpcaddr 0.0.0.0 --rpcaddr 0.0.0.0 --rpc --http --http.api eth,net,web3,txpool
```

should be 

```
geth --classic --datadir /opt/etc --http  --http.vhosts * --http.addr 0.0.0.0 --http.api eth,net,web3,txpool
```

**Comment by zhangsj** [comment]
can not fix
![image](https://user-images.githubusercontent.com/7639036/94360899-3fa0a180-00e3-11eb-9961-f5e723a73426.png)

![image](https://user-images.githubusercontent.com/7639036/94360886-331c4900-00e3-11eb-836b-602b5c999b23.png)

**Comment by meowsbits** [comment]
Hm, interesting. Thanks for your report.

This looks like a known/reported error at upstream:

- https://github.com/ethereum/go-ethereum/issues/21496
- https://github.com/ethereum/go-ethereum/issues/21421
- https://github.com/ethereum/go-ethereum/issues/20190
- https://github.com/ethereum/go-ethereum/issues/18994
- https://github.com/ethereum/go-ethereum/issues/18388#issuecomment-460566250
- https://github.com/ethereum/go-ethereum/issues/19305

Please see Peter's comment at: https://github.com/ethereum/go-ethereum/issues/21496#issuecomment-685740644 for instructions toward recovery (noting that you'll want to replace the block number with one pertinent to your situation). 

Also, if you're able and willing help us out with debugging (before attempting to fix), it would be great to see logs if you run `--vmodule=downloader=5` so we can see exactly which blocks are causing the issue, and if possible, to upload your `chaindata` directory somewhere so we can examine it.

Just for reference, here's the flow causing the error at ethereum/go-ethereum (same logic) - https://github.com/ethereum/go-ethereum/blob/master/eth/downloader/downloader.go#L936

**Comment by meowsbits** [comment]
Getting reports that this has been reproduced by a couple of others with upgrade to v1.11.15
