### ISSUE TITLE
Sync is really slow on fresh ETC node when syncing the last year

### ISSUE THREAD

**Issue by gal432** [etclabscore/core-geth#205]
#### System information

Geth version: `1.11.15-stable`
OS & Version: Linux (`uname -a: Linux etc-mainnet-0 4.14.174+ #1 SMP Fri Sep 4 17:56:58 PDT 2020 x86_64 Linux`, official docker image)

#### Expected behaviour
Sync will be done after 3 days

#### Actual behaviour
Sync is still running

#### Description
Hello. I'm trying to sync my new ETC node to the chain.
I'm using the docker version `etclabscore/core-geth:version-1.11.15` with the following parameters:

```
geth --maxpeers 100 --http --http.addr 0.0.0.0 --http.port 8345 --http.corsdomain * --http.vhosts * --http.api debug,web3,eth,txpool,personal,net --syncmode full --datadir /data --cache 4096 --classic
```

In the beginning the sync was really fast and we closed 4 years of the network with less then 24h.
But now it takes a ~12h to complete the sync of 2m.

Right now I'm on block number `8886899` with age of `1y2w2d`.
What can I do to improve the sync? I tried to increase the cache (from 2K to 4K) and It seems like it didn't help much, and it doesn't sounds me right to wait two weeks to let the node to finish the sync.
Attaching the logs from the last few hours

[null__logs__2020-10-10T11-19.txt](https://github.com/etclabscore/core-geth/files/5358651/null__logs__2020-10-10T11-19.txt)

**Comment by meowsbits** [comment]
That chapter of the chain's history (8.8M-~9.1M, ish) is very slow to sync; it's when the dust-cleaning contracts were called to remove empty states per EIP-161. It should speed up again once these calls are done.
