### ISSUE TITLE
no mining work available yet

### ISSUE THREAD

**Issue by q9f** [etclabscore/core-geth#207]
#### System information

Geth version: `v1.11.15-stable-51c7e458`
OS & Version: Linux

#### Expected behaviour
Should serve `eth_getWork`

#### Actual behaviour
Does not serve `eth_getWork` api unless you turn on the CPU miner with `miner.start(1)`

#### Steps to reproduce the behaviour
1. launch `geth --http`
2. point `ethminer` to `getwork://127.0.0.1:8545`
3. get `no mining work available yet`

```
WARN [10-12|09:36:48.783] Served eth_getWork                       conn=127.0.0.1:47976 reqid=1 t="57.828µs" err="no mining work available yet"
```

**Comment by meowsbits** [comment]
Running with `geth --mine --http` should fix this (add the `--mine` flag).

**Comment by meowsbits** [comment]
@q9f Does this resolve the issue for you?

**Comment by q9f** [comment]
Yes. My point was that I don't want to mine on CPU but on GPU, so I do not want the `--mine` flag. If this is intended behaviour, then we can close this though.

**Comment by meowsbits** [comment]
Yea, this is intended behavior. Mining with CPU requires `--miner.threads=<1+>`.

**Comment by q9f** [comment]
> Yea, this is intended behavior. Mining with CPU requires `--miner.threads=<1+>`.

Just to be clear, I want to mine on GPU not CPU.
