### ISSUE TITLE
Warning signal: Ancestor below allowance

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [etclabscore/core-geth#221]
Hey guys, there is someone having problems with the newest Core-Geth. In general it works.

![image](https://user-images.githubusercontent.com/48069525/98045022-24cef480-1e28-11eb-8f20-5502161c894e.png)
![image](https://user-images.githubusercontent.com/48069525/98045040-2a2c3f00-1e28-11eb-9abd-434c963a3703.png)

Could you pls look into it? If you need further infos, let me know. Thx!

**Comment by meowsbits** [comment]
Things appear normal in these images. 

The `Ancestor below allowance` line suggests that the peer was useless (eg. wrong chain) and, as is visible in the following line `Syncronization failed, dropping peer`, gets dropped. 

Imports appear to be functioning and corresponding with contemporary canonical blocks. 

As the node's peer list firms up, these peer negotiation warnings should become less frequent.

**Comment by TheEnthusiasticAs** [comment]
okidoki, thx!

**Comment by TheEnthusiasticAs** [comment]
An update from the same miner: After updating to the v.1.11.17 the above issue was gone. If you need a log file to analyse it and use the infos in future releases, let me know.
