### ISSUE TITLE
Handle default datadir in the help section of geth command for `--ethash.dagdir`

### ISSUE THREAD

**Issue by ziogaschr** [etclabscore/core-geth#247]
The default datadir in the help section of geth command for `--ethash.dagdir` is not always correct.

There is no broken functionality or anything. The help text needs to be changed only.

#### System information

```
CoreGeth
Version: 1.11.20-unstableArchitecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.5
Operating System: darwin
GOPATH=/Users/ziogaschr/Sites/go
GOROOT=/usr/local/Cellar/go/1.15.5/libexec
```

#### Expected behaviour

For **classic** and **mordor** it should print `~/Library/Etchash`

#### Actual behaviour

It prints `~/Library/Ethash`

#### Steps to reproduce the behaviour

```bash
> geth --help | grep dag   
  makedag                            Generate ethash mining DAG (for testing)  
  --ethash.dagdir value               Directory to store the ethash mining DAGs (default: "/Users/ziogaschr/Library/Ethash")  
  --ethash.dagsinmem value            Number of recent ethash mining DAGs to keep in memory (1+GB each) (default: 1)
  --ethash.dagsondisk value           Number of recent ethash mining DAGs to keep on disk (1+GB each) (default: 2)
  --ethash.dagslockmmap               Lock memory maps for recent ethash mining DAGs
```

**Comment by ziogaschr** [comment]
It's hard to handle this case, as for being accurate the end user has to check help by passing the correct network used like `geth --classic --help`.

I would suggest changing the help text to something like: `Directory to store the ethash mining DAGs (default: "/Users/ziogaschr/Library/Ethash") or the etchash mining DAGs (default: "/Users/ziogaschr/Library/Etchash") based on supported network`

@iquidus what's your opinion?

**Comment by iquidus** [comment]
Yeah at present the default locations only change when --classic or --mordor flags are active. However

`Directory to store the ethash mining DAGs (default: "/Users/ziogaschr/Library/Ethash") or the etchash mining DAGs (default: "/Users/ziogaschr/Library/Etchash") based on supported network` seems to long imo. 

Perhaps we could get away with something like: `Directory to store the [ethash|etchash] mining DAGs (default: "/Users/ziogaschr/Library/[Ethash|Etchash]") based on supported network.`

**Comment by meowsbits** [comment]
Speaking of this, Mordor and Classic Mainnet default DAG dirs are both `$HOME/.etchash`, right? So if I run them both (either at the same time, or one after the other), there will be either a collision or conflict causing regeneration, or?

**Comment by ziogaschr** [comment]
Good point. @iquidus knows more about it. But I believe, both Mordor and Classic will use the same dir and regenerate the ones needed. The only issue might be, in case someone is around the ECIP1099 transition at Mordor and then starts a Classic node using the same cached DAGs. The problem will be that the hashed filename will match, while the content will be different.

@iquidus can you verify it?

**Comment by iquidus** [comment]
due to the defaults for DAGs/caches on disk + the distance between mordor and mainnet, this scenario shouldnt occur. However yes, it would otherwise, in which case we may want to consider ~/.etchash-mordor for example. However for now I think leaving as is works fine for the existing networks.

**Comment by iquidus** [comment]
running both at same time however may be problematic and warrants further testing. (one instance may try clean the files of the other?)

**Comment by ziogaschr** [comment]
This will probably be the problem for private networks as well. 
I suggest, leaving the same folder at this point as some node owners might have created scripts using this path at the moment. 
On the other hand we can document, that when running multiple chains on same machine, it is advised to always set `--ethash.dagdir`
