### ISSUE TITLE
eth_blockNumber 0

### ISSUE THREAD

**Issue by abyssal0** [etclabscore/core-geth#267]
When synchronizing blocks, the synchronization speed slows down to the last few dozen blocks each time, and then the number of query blocks is always 0 because it cannot catch up with the latest block.

{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}
{"jsonrpc":"2.0","id":1,"result":"0x0"}

How can I solve this problem

**Comment by meowsbits** [comment]
Hi there! :wave:  Please include some information that will help us debug this issue with you:

- Output of `geth version`
- What configuration are you running geth with? (What is the command you use to run it?)
- Relevant system information, eg. Hard drive or SSD?
- How long has this been happening?

**Comment by abyssal0** [comment]
A day later the block caught up
