### ISSUE TITLE
cmd/faucet: -attach has unhandled case when rpc errors

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/core-geth#280]
#### System information

Geth version: 

```
CoreGeth
Version: 1.11.21-unstable
Git Commit: 8ffc0959c92460e32f94484c1aed62de857d50f8
Git Commit Date: 20210105
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.5
Operating System: linux
GOPATH=/root/go
GOROOT=/usr/local/go
```

#### Expected behaviour

Using `-attach` connects to a running client. If the running client quits or otherwise has connection issues, a re-connection is attempted indefinitely until succeeding.

#### Actual behaviour

A closed connection yields a permanently failed connection and faucet stalls.

#### Steps to reproduce the behaviour

Restart the target client for `-attach`.

#### Backtrace

````
Jan 08 04:54:11 sf-etclabs sh[5312]: INFO [01-08|04:54:11.573] Updated faucet state                     number=3038886 hash="4a1428…f970aa" age=5s    balance=607287648139897440811633 nonce=279023 price=1000000000                                                             
Jan 08 04:55:11 sf-etclabs sh[5312]: WARN [01-08|04:55:11.273] Failed to update faucet state            block=3038887 hash="c9f79b…1947db" err="context deadline exceeded"                                                                                                       
Jan 08 04:55:17 sf-etclabs sh[5312]: DEBUG[01-08|04:55:14.012] Unsolicited RPC response                 reqid=74146
Jan 08 04:55:37 sf-etclabs sh[5312]: WARN [01-08|04:55:31.500] Failed to update faucet state            block=3038888 hash="04bb5e…9863cc" err="context deadline exceeded"                                                                                                       
Jan 08 04:56:20 sf-etclabs sh[5312]: DEBUG[01-08|04:56:20.703] RPC connection read error                err=EOF
Jan 08 15:44:50 sf-etclabs systemd[1]: Stopping FaucetMordor...
````

**Comment by meowsbits** [comment]
On second thought... instead of resolving this by introducing retries (which can be a very complex rabbit hole), I think the faucet should just `Fatal` when the connection it depends on gives a connection error. RPC client retries can and should be its own thing, and should be addressed in the context of the RPC package rather than the faucet.

**Comment by ziogaschr** [comment]
Indeed, I worked on introducing retries which is not cleanest thing to do, as you don't really know the reason connection closed.

> I think the faucet should just Fatal when the connection it depends on gives a connection error.

This makes sense, my only worry is that, most of the time, someone want to start faucet and forget it. So this fatal will request him monitoring it more carefully, on the other hand there is no reason for the node to which is attached to close.

I am wondering, if at the end because of this, people will prefer running on syncmode rather than attach.

**Comment by meowsbits** [comment]
> introducing retries which is not cleanest thing to do, as you don't really know the reason connection closed.

Indeed. Even if you know _why_ it closed, handling retries can be tricky... for example https://github.com/grpc/proposal/blob/master/A6-client-retries.md, ~~where `ethereum/go-ethereum/rpc` has no retry logic~~ does it simply: https://github.com/etclabscore/core-geth/blob/master/rpc/client.go#L201.

Update from discord:

![image](https://user-images.githubusercontent.com/45600330/104189221-006f3580-53e0-11eb-9ac3-d61c18ccccca.png)

From this: the issue isn't the RPC connection, which will attempt reconnect. Instead, the issue is specifically the `newHeads` subscription, which needs to be reestablished.

**Comment by meowsbits** [comment]
> I am wondering, if at the end because of this, people will prefer running on syncmode rather than attach.

While I won't try to speak for most people, _I_ like to use the `-attach` feature because
- it avoids duplicate chaindata
- I use `systemd` to manage restart in case of failure
