### ISSUE TITLE
rpc: discovery to return correct link for methods' externalDocs

### ISSUE THREAD

**Issue by ziogaschr** [etclabscore/core-geth#297]
Calling the `rpc_discover` gives wrong links to our repo codebase.

#### System information

```
CoreGeth
Version: 1.11.21-unstable
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.5
Operating System: darwin
GOPATH=/Users/ziogaschr/Sites/go
GOROOT=/usr/local/Cellar/go/1.15.5/libexec
```

#### Expected behaviour
To point at our repo `etclabscore/core-geth`

```
"externalDocs": {
        "description": "Github remote link",
        "url": "https://github.com/etclabscore/core-geth/blob/master/internal/ethapi/api.go#L2004"
      }
```

#### Actual behaviour

It points at Ethereum repo `ethereum/go-ethereum`

```
"externalDocs": {
        "description": "Github remote link",
        "url": "https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L2004"
      }
```

**Comment by meowsbits** [comment]
Of note here is that github.com/etclabscore/core-geth is, for the purposes of `go` at least, declared as `github.com/ethereum/go-ethereum` (https://github.com/etclabscore/core-geth/blob/master/go.mod#L1)
