### ISSUE TITLE
How to return tokens from the BEP-20 network from a Geth-based wallet?

### ISSUE THREAD

**Issue by andrandrandr** [etclabscore/core-geth#316]
Hello! Accidentally sent Eth from the exchange in the BEP-20 network (binance) to a wallet that is made on the basis of Geth. How can I send the tokens back?

**Comment by meowsbits** [comment]
Sounds like this question is a great candidate for https://ethereum.stackexchange.com/ or similar. 

The core-geth API documentation for `eth_sendTransaction` can be found here: https://etclabscore.github.io/core-geth/JSON-RPC-API/modules/eth/#eth_sendtransaction.
