### ISSUE TITLE
Uncle blocks are missing in eth_getBlockByHash RPC response

### ISSUE THREAD

**Issue by APshenkin** [etclabscore/core-geth#332]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.11.22`
OS & Version: Windows/Linux/OSX Docker
Commit hash : (if `develop`)

#### Expected behaviour
eth_getBlockByHash should return uncles in data as array

#### Actual behaviour
uncles are missing

#### Steps to reproduce the behaviour
```
curl --location --request POST 'https://myetcnode.com' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "eth_getBlockByHash",
    "params": [
        "0x2733c5587974f120453b556a71bf096199c587b5a530d98d6a4d6a1746ec967b",
        true
    ],
    "id": 83
}'
```

**Comment by APshenkin** [comment]
Also eth_getBlockByHash don't return transactions array if it's empty. Seems like some issue with serialization? (it removes empty arrays from response)

**Comment by APshenkin** [comment]
Seems related to this code. https://github.com/etclabscore/core-geth/blob/73e58be77b18830b2a71f3d9bb1e1d7963d4f975/internal/ethapi/api.go#L1220

omitempty should be removed

**Comment by meowsbits** [comment]
Yeap, I think you're right on. Will have a PR in today fixing this. Good catch, thank you!
