### ISSUE TITLE
EIP 3436 Clique Block Choice Rule

### ISSUE THREAD

**Issue by q9f** [etclabscore/core-geth#358]
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-3436.md

1. Choose the block with the most total difficulty.
2. Then choose the block with the lowest block number.
3. Then choose the block whose validator had the least recent in-turn block assignment.
4. Then choose the block with the lowest hash.

**Comment by q9f** [comment]
https://ethereum-magicians.org/t/eip-3436-expanded-clique-block-choice-rule/5809

**Comment by meowsbits** [comment]
> __The current specification of Clique allows for multiple competing blocks from producers but does not provide any strategies to pick blocks aside from the current "highest total difficulty" rule.__ This EIP proposes a four step choice rule of highest total difficulty, shortest chain, most recently in-turn, and lowest hash. This would prevent deadlocks that have occurred in production systems.

https://eips.ethereum.org/EIPS/eip-225: Clique proof-of-authority consensus protocol

**Comment by meowsbits** [comment]
A screen shot taken during the latest deadlock on Kotti.

![2021-04-06-073308_1886x551_screenshot](https://user-images.githubusercontent.com/45600330/115024250-71156a80-9e85-11eb-9b96-542d97cfe049.png)

![image](https://user-images.githubusercontent.com/45600330/115026277-ebdf8500-9e87-11eb-8ff1-4312cf8eedc9.png)
