### ISSUE TITLE
feature: chain-dependent protocol defaults

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/core-geth#382]
Extending issue in #381 to a more general case; proposing a core-geth design where protocol defaults can be defined on a per-chain basis. 
This way the ancient `eth/63` protocol won't need to also be available for networks like ETH.

**Comment by ziogaschr** [comment]
It might worth collecting such protocol defaults here to have a list of them.

**Comment by meowsbits** [comment]
- classic `66,65,64,63` (with the deprecated `64,63` temporarily continued for Mantis compatibility)
- mordor, kotti `66,65,64,63` (ditto)
- eth, ropsten, goerli, rinkeby, flavor-of-the-week testnet: `66,65`

**Comment by meowsbits** [comment]
[Besu supports `eth/65`.](https://discord.com/channels/223674353001168906/223675625334898688/842869467197341707)

**Comment by ziogaschr** [comment]
Resolved with #384
