### ISSUE TITLE
set up ETC DNS discovery

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/core-geth#39]
[ethereum/go-ethereum from v1.9.11](https://github.com/ethereum/go-ethereum/releases/tag/v1.9.11) implements DNS-based peer discovery, currently only supporting Foundation networks.

This ticket is for implementing the same for Classic.

Rel #37

**Comment by q9f** [comment]
Oh, yes please!

**Comment by meowsbits** [comment]
https://github.com/etclabscore/discv4-dns-lists

am running a test cycle now and will push there when aok.

**Comment by meowsbits** [comment]
am running a test cycle now and will push there when aok.

**Comment by meowsbits** [comment]
Finally merged with #47
