### ISSUE TITLE
tests (CI): faucet#TestFacebook: no ethereum address found to fund

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/core-geth#391]
This test has been seen initially by @ziogaschr failing before on Travis, too, during development.
Neither of us can reproduce it locally. 

https://travis-ci.org/github/etclabscore/core-geth/jobs/773517402
https://github.com/etclabscore/core-geth/commit/e9b5f6068ebfa4445fa66ad126d29b5ae9adaebb

```
INFO [06-04|17:39:43.045] Checking datadir migration               datadir=/tmp/faucet-migration-test-datadir-1622828383044933086/mychain

WARN [06-04|17:39:43.045] Found existing 'MultiFaucet' directory, migrating old=/tmp/faucet-migration-test-datadir-1622828383044933086/mychain/MultiFaucet new=/tmp/faucet-migration-test-datadir-1622828383044933086/mychain/CoreFaucet

--- FAIL: TestFacebook (0.92s)

    faucet_test.go:62: No Ethereum address found to fund

FAIL

FAIL	github.com/ethereum/go-ethereum/cmd/faucet	0.958s
```

**Comment by ziogaschr** [comment]
I wonder if this is because TravisCI added some firewall rules. It also fails for me if I don't allow it through my firewall.

**Comment by meowsbits** [comment]
For some reason it wants Travis to log in to access the content. 

https://travis-ci.org/github/meowsbits/core-geth/jobs/773787622

![image](https://user-images.githubusercontent.com/45600330/121025684-0ab51600-c76b-11eb-8ea9-df8e8e52f9a8.png)
