### ISSUE TITLE
Failed to read account password contents(faucet.exe)

### ISSUE THREAD

**Issue by zrock23** [etclabscore/core-geth#404]
faucet.exe....

←[32mINFO ←[0m[08-22|05:19:56.794] Using chain/net config                   ←[32mnetwork id←[0m=4 ←[32mbootnodes←[0m=enode://a24ac7c5484ef4ed0c5eb2d36620ba4e4aa13b8c84684e1b4aab0cebea2ae45cb4d375b77eab56516d34bfbd3c1a833fc51296ff084b770b94fb9028c4d25ccf@52.169.42.101:30303 ←[32mchain config←[0m="{ChainID: 4 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 1035301 Constantinople: 3660663 ConstantinopleFix: 4321234 Istanbul: 5435345 MuirGlacier: <nil> Berlin: 8290928 Engine: ethash}"
←[35mCRIT ←[0m[08-22|05:19:56.808] Failed to read account password contents ←[35mfile←[0m= ←[35merr←[0m="open : The system cannot find the file specified."

what does this mean?
I do not understand anything significant anymore?

**Comment by meowsbits** [comment]
The `faucet` program sends transactions (transferring funds). The faucet needs to use a key to sign these transactions (a keyfile for an account having some balance that you wish to distribute). For this, you need to use these two flags:

```
--account.json=/path/to/keyfile.json \
--account.pass=/path/to/password.txt
```

**Comment by zrock23** [comment]
faucet.exe...
←[32mINFO ←[0m[08-24|18:59:07.420] Using chain/net config                   ←[32mnetwork id←[0m=4 ←[32mbootnodes←[0m=enode://a24ac7c5484ef4ed0c5eb2d36620ba4e4aa13b8c84684e1b4aab0cebea2ae45cb4d375b77eab56516d34bfbd3c1a833fc51296ff084b770b94fb9028c4d25ccf@52.169.42.101:30303 ←[32mchain config←[0m="{ChainID: 4 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 1035301 Constantinople: 3660663 ConstantinopleFix: 4321234 Istanbul: 5435345 MuirGlacier: <nil> Berlin: 8290928 Engine: ethash}"
←[32mINFO ←[0m[08-24|18:59:07.446] Persisted trie from memory database      ←[32mnodes←[0m=356 ←[32msize←[0m=50.51KiB ←[32mtime←[0m=1.1222ms ←[32mgcnodes←[0m=0 ←[32mgcsize←[0m=0.00B ←[32mgctime←[0m=0s ←[32mlivenodes←[0m=1 ←[32mlivesize←[0m=0.00B
←[32mINFO ←[0m[08-24|18:59:09.760] Starting faucet client stack
←[32mINFO ←[0m[08-24|18:59:09.764] Persisted trie from memory database      ←[32mnodes←[0m=356 ←[32msize←[0m=50.51KiB ←[32mtime←[0m=1.037ms  ←[32mgcnodes←[0m=0 ←[32mgcsize←[0m=0.00B ←[32mgctime←[0m=0s ←[32mlivenodes←[0m=1 ←[32mlivesize←[0m=0.00B
←[32mINFO ←[0m[08-24|18:59:09.764] Checking datadir migration               ←[32mdatadir←[0m="C:\\Users\\Petar Toshev\\Desktop\\data2\\data2"
←[32mINFO ←[0m[08-24|18:59:09.771] Persisted trie from memory database      ←[32mnodes←[0m=356 ←[32msize←[0m=50.51KiB ←[32mtime←[0m=1.0435ms ←[32mgcnodes←[0m=0 ←[32mgcsize←[0m=0.00B ←[32mgctime←[0m=0s ←[32mlivenodes←[0m=1 ←[32mlivesize←[0m=0.00B
←[32mINFO ←[0m[08-24|18:59:09.771] Config discovery                         ←[32murls←[0m=[]
←[32mINFO ←[0m[08-24|18:59:09.771] Allocated trie memory caches             ←[32mclean←[0m=154.00MiB ←[32mdirty←[0m=256.00MiB
←[32mINFO ←[0m[08-24|18:59:09.771] Allocated cache and file handles         ←[32mdatabase←[0m="C:\\Users\\Petar Toshev\\Desktop\\data2\\data2\\CoreFaucet\\chaindata" ←[32mcache←[0m=512.00MiB ←[32mhandles←[0m=16
←[32mINFO ←[0m[08-24|18:59:10.039] Opened ancient database                  ←[32mdatabase←[0m="C:\\Users\\Petar Toshev\\Desktop\\data2\\data2\\CoreFaucet\\chaindata\\ancient" ←[32mreadonly←[0m=false
←[32mINFO ←[0m[08-24|18:59:10.044] Persisted trie from memory database      ←[32mnodes←[0m=356 ←[32msize←[0m=50.51KiB ←[32mtime←[0m=0s       ←[32mgcnodes←[0m=0 ←[32mgcsize←[0m=0.00B ←[32mgctime←[0m=0s ←[32mlivenodes←[0m=1 ←[32mlivesize←[0m=0.00B
←[32mINFO ←[0m[08-24|18:59:10.045] Found stored genesis block               ←[32mconfig←[0m="{ChainID: 4 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 1035301 Constantinople: 3660663 ConstantinopleFix: 4321234 Istanbul: 5435345 MuirGlacier: <nil> Berlin: 8290928 Engine: ethash}"
←[32mINFO ←[0m[08-24|18:59:10.045] Initialised chain configuration          ←[32mconfig←[0m="{ChainID: 4 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 1035301 Constantinople: 3660663 ConstantinopleFix: 4321234 Istanbul: 5435345 MuirGlacier: <nil> Berlin: 8290928 Engine: ethash}"
←[32mINFO ←[0m[08-24|18:59:10.049] Disk storage enabled for ethash caches   ←[32mdir←[0m="C:\\Users\\Petar Toshev\\Desktop\\data2\\data2\\CoreFaucet\\ethash" ←[32mcount←[0m=3
←[32mINFO ←[0m[08-24|18:59:10.049] Disk storage enabled for ethash DAGs     ←[32mdir←[0m="C:\\Users\\Petar Toshev\\AppData\\Local\\Ethash" ←[32mcount←[0m=2
←[32mINFO ←[0m[08-24|18:59:10.049] Initialising Ethereum protocol           ←[32mnetwork←[0m=4 ←[32mdbversion←[0m=8
←[32mINFO ←[0m[08-24|18:59:10.051] Loaded most recent local header          ←[32mnumber←[0m=0 ←[32mhash←[0m=75fb57..7216ad ←[32mtd←[0m=1 ←[32mage←[0m=4y5mo5d
←[32mINFO ←[0m[08-24|18:59:10.051] Loaded most recent local full block      ←[32mnumber←[0m=0 ←[32mhash←[0m=75fb57..7216ad ←[32mtd←[0m=1 ←[32mage←[0m=4y5mo5d
←[32mINFO ←[0m[08-24|18:59:10.051] Loaded most recent local fast block      ←[32mnumber←[0m=0 ←[32mhash←[0m=75fb57..7216ad ←[32mtd←[0m=1 ←[32mage←[0m=4y5mo5d
←[33mWARN ←[0m[08-24|18:59:10.052] Loaded snapshot journal                  ←[33mdiskroot←[0m=509e63..0f3f0b ←[33mdiffs←[0m=missing
←[32mINFO ←[0m[08-24|18:59:10.053] Loaded local transaction journal         ←[32mtransactions←[0m=0 ←[32mdropped←[0m=0
←[32mINFO ←[0m[08-24|18:59:10.056] Regenerated local transaction journal    ←[32mtransactions←[0m=0 ←[32maccounts←[0m=0
←[33mWARN ←[0m[08-24|18:59:10.058] Unclean shutdown detected                ←[33mbooted←[0m=2021-08-24T18:56:46+0300 ←[33mage←[0m=2m24s
←[33mWARN ←[0m[08-24|18:59:10.058] Unclean shutdown detected                ←[33mbooted←[0m=2021-08-24T18:58:03+0300 ←[33mage←[0m=1m7s
←[32mINFO ←[0m[08-24|18:59:10.059] Starting peer-to-peer node               ←[32minstance←[0m=CoreGeth/v1.12.0-stable-c5ef3a9e/windows-amd64/go1.16.3
←[32mINFO ←[0m[08-24|18:59:10.274] New local node record                    ←[32mseq←[0m=3 ←[32mid←[0m=733120a545748ad8 ←[32mip←[0m=127.0.0.1 ←[32mudp←[0m=30303 ←[32mtcp←[0m=30303
←[32mINFO ←[0m[08-24|18:59:10.274] Started P2P networking                   ←[32mself←[0m=enode://14f15454a3fa831b1401b972f6a243fd0106b2e42725cc64d73734d7294061d97cc3f2579d0bc567668c93ecd4242b96393425c8ac058988f59493f1640df522@127.0.0.1:30303
←[32mINFO ←[0m[08-24|18:59:10.275] Stats daemon started
←[32mINFO ←[0m[08-24|19:02:38.280] Looking for peers                        ←[32mpeercount←[0m=1 ←[32mtried←[0m=0 ←[32mstatic←[0m=0
←[32mINFO ←[0m[08-24|19:03:13.217] Looking for peers                        ←[32mpeercount←[0m=1 ←[32mtried←[0m=0 ←[32mstatic←[0m=0
←[32mINFO ←[0m[08-24|19:03:48.234] Looking for peers                        ←[32mpeercount←[0m=1 ←[32mtried←[0m=0 ←[32mstatic←[0m=0

I think I succeeded, I still don't understand how to enter a command or what is the idea of this subroutine I want a little help from a team? 👍

**Comment by meowsbits** [comment]
It's unclear to me what exactly we need to do to help you. Do you want information about what the `faucet` program is? Do you have a use case we can help you approach?

**Comment by zrock23** [comment]
hello from the above answer of your colleague I understood how the program works, but I don't think it is anything more than a wallet with an api extension for displaying statistics!  If you think there is anything else, write to me.

**Comment by meowsbits** [comment]
The faucet program provides a way to distribute funds from an account to people who request tokens (usually for testnets). The request system uses a 3rd party authentication pattern to prevent spam and rate limit requests. It serves a basic webpage to facilitate this interaction. On the backend, it can be responsible for running a light client or it can `attach` to an already-running API.
