### ISSUE TITLE
When will v1.12.1 publish to docker hub

### ISSUE THREAD

**Issue by vae520283995** [etclabscore/core-geth#409]
I hope to update to the latest version as soon as possible to prevent the vulnerability from being attacked

**Comment by brucexiu** [comment]
Please push the image to docker hub ASAP. Thanks.

**Comment by 1scrooge** [comment]
I also need a new docker image

**Comment by jithin03** [comment]
Please release the latest images

**Comment by ziogaschr** [comment]
We will upload them asap (during this week). We had some issues with CI system holding the keys and uploading the Docker images

**Comment by meowsbits** [comment]
Docker hub is updated now with latest versions.
