### ISSUE TITLE
Missing coregeth 1.12.1 in files core-geth-alltools-linux-v1.12.1.zip and core-geth-linux-v1.12.1.zip

### ISSUE THREAD

**Issue by zrock23** [etclabscore/core-geth#410]
why is the file uploaded with geth 1.9.26 unstable content? Missing coregeth 1.12.1 as well as faucet!

**Comment by ziogaschr** [comment]
Downloading this [core-geth-linux-v1.12.1.zip](https://github.com/etclabscore/core-geth/releases/download/v1.12.1/core-geth-linux-v1.12.1.zip)

Gives back:

```bash
~ ./geth version
CoreGeth
Version: 1.12.1-stable
Git Commit: 04d026e226c55216deafadd4e4b06d144922a6e4
Architecture: amd64
Go Version: go1.16.2
Operating System: linux
GOPATH=/home/liot/go
GOROOT=/usr/local/go
```

Downloading this [core-geth-alltools-linux-v1.12.1.zip](https://github.com/etclabscore/core-geth/releases/download/v1.12.1/core-geth-alltools-linux-v1.12.1.zip)

Gives back:

```bash
~ ./geth version
CoreGeth
Version: 1.12.1-stable
Git Commit: 04d026e226c55216deafadd4e4b06d144922a6e4
Architecture: amd64
Go Version: go1.16.2
Operating System: linux
GOPATH=/home/liot/go
GOROOT=/usr/local/go
```

And also includes faucet:

```bash
~ ls 
abidump  ancient-store-mem  clef        ethkey  geth
abigen   bootnode           devp2p      evm     p2psim
ageth    checkpoint-admin   echainspec  faucet  rlpdump
```

@zrock23 can you please point to the files with the wrong version. Thanks

**Comment by meowsbits** [comment]
>  geth 1.9.26 unstable content

This number seems like a strange one for this repository; it looks like an ethereum/go-ethereum tag number.

**Comment by zrock23** [comment]
oh to handle the error is mine, i hadn't installed go-goland properly!

**Comment by meowsbits** [comment]
Thanks for the follow up! Happy hacking.
