### ISSUE TITLE
Support EVMC6

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/core-geth#55]
This would enable SSVM integration via `ssvm-evmc` and others. 

### Resources
- :fast_forward:  https://github.com/ethereum/go-ethereum/pull/17954
- https://github.com/ethereum/go-ethereum/compare/master...ewasm:ewasm-testnet-milestone1?expand=1

#### EVMC
- https://github.com/ethereum/evmc
- https://evmc.ethereum.org/

#### SSVM
- https://github.com/second-state/SSVM#build-ssvm
- https://hackmd.io/MOOoRHVmSi2E3rL9CgOayg?view=

#### Hera
- https://github.com/ewasm/hera#building-hera
- https://github.com/ewasm/testnet#geth--hera

#### SputnikVM
- etclabscore/go-ethereum with SputnikVM: https://github.com/etclabscore/go-ethereum/blob/development/core/multivm_processor.go

**Comment by dm4** [comment]
Hi, I am a developer of SSVM. If there is any problem about SSVM integration please let me kown.
Thanks!

**Comment by meowsbits** [comment]
@dm4 Is SSVM intending support for EVMC v7.x?

https://github.com/ethereum/evmc/releases

**Comment by meowsbits** [comment]
Closing, since #57 has been merged! :crossed_flags: :rocket:
