### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/core-geth#61]
Parent/tracking issue for documentation improvement in general.

- Install
- broken resources
- Integrate with https://github.com/etclabscore/core-geth-website/tree/master/src/docs

**Comment by ziogaschr** [comment]
@meowsbits do you think more on this for now? Can we close this issue?

**Comment by meowsbits** [comment]
Yeap, much better than it was, and I haven't found any outstanding issues lurking since our last changes.
