### ISSUE TITLE
docs/core: handle these

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/core-geth#69]
I kind of hid them there with #60 ... they are just loosely-categorized docs taken cut-and-paste from the original README.md. 

- [ ] revise them to fit core-geth better, vs. go-ethereum. 
  - [ ] fix links
  - [ ] tweak cli flags/usage
  - [ ] update ./cmd/ directory information
- [ ] integrate them with http://core-geth.org somehow. 

Rel #61

**Comment by ziogaschr** [comment]
Some work has been done towards this at #291. So now, we can work on the content of the Markdown pages.

**Comment by meowsbits** [comment]
Indeed. I'm going to close this since we have rather handled the `docs/core`, and we can create a new issue(s) for further documentation efforts as required.
