### ISSUE TITLE
move multi-geth to own repository; consider rebrand

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/core-geth#7]
Migrated from: https://api.github.com/repos/etclabscore/multi-geth-fork/issues/146
Original author: @soc1c

---

this should be a top level repository to indicate the state of the code.

upstream compatibility with multi-geth and foundation geth can still be maintained.

we should consider a rebrand to distinguish from multi-geth releases that eventually will happen. what about `phoenix-geth` with client identifier `phoenix`?

**Comment by meowsbits** [comment]
Done.

**Comment by soc1c** [comment]
Your migration script didn't actually transfer the issue :D
