### ISSUE TITLE
rpc api: eth.getHashrate() != miner.getHashrate()

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/core-geth#79]
```
> console.log(Date(), web3.version.node, eth.blockNumber, eth.syncing, admin.peers.length, eth.mining, eth.getHashrate(), miner.getHashrate());          
Sat, 21 Mar 2020 10:49:30 UTC CoreGeth/v1.11.2-stable-cbe4a649/linux-amd64/go1.13.5 1082159 false 12 true undefined 0     
```

**Comment by q9f** [comment]
That's also true for Foundation Geth.

**Comment by meowsbits** [comment]
https://github.com/ethereum/go-ethereum/pull/20802

**Comment by meowsbits** [comment]
This has essentially been labeled `wontfix` upstream. We'll defer to their opinion here for the sake of code congruence. https://github.com/ethereum/go-ethereum/pull/20802#issuecomment-608587523
