### ISSUE TITLE
Error Make all

### ISSUE THREAD

**Issue by malefol7** [etclabscore/core-geth#91]
ubuntu 16.04
actual run parity 2.7

@virtualmin:~/core-geth$ make all
env GO111MODULE=on go run build/ci.go install
build/ci.go:61:2: cannot find package "github.com/cespare/cp" in any of:
        /usr/local/go/src/github.com/cespare/cp (from $GOROOT)
        /home/malefol/go/src/github.com/cespare/cp (from $GOPATH)
build/ci.go:62:2: cannot find package "github.com/ethereum/go-ethereum/internal/build" in any of:
        /usr/local/go/src/github.com/ethereum/go-ethereum/internal/build (from $GOROOT)
        /home/malefol/go/src/github.com/ethereum/go-ethereum/internal/build (from $GOPATH)
build/ci.go:63:2: cannot find package "github.com/ethereum/go-ethereum/params" in any of:
        /usr/local/go/src/github.com/ethereum/go-ethereum/params (from $GOROOT)
        /home/malefol/go/src/github.com/ethereum/go-ethereum/params (from $GOPATH)
Makefile:21: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 1

**Comment by meowsbits** [comment]
What is your Go version?  Please try upgrading to Go v1.13

**Comment by malefol7** [comment]
ok problem solved, upgraded go version >= 1.13 thanks

https://gist.github.com/nikhita/432436d570b89cab172dcf2894465753
